### ISSUE TITLE
Doc needs update for uuid

### ISSUE THREAD

**Issue by sgup** [imagekit-developer/imagekit-javascript#2]
Don't know where to report this. On this doc section:

https://docs.imagekit.io/imagekit-docs/client-side-file-upload#signature-generation-for-client-side-file-upload

Using `node-uuid` like that is now deprecated, see: https://github.com/kelektiv/node-uuid#uuid

**Comment by imagekitio** [comment]
Thanks @sgup, we will fix this and release an update soon.
