### ISSUE TITLE
Wrong parameter name for border

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-javascript#23]
The right parameter name for the border is `b` as per [the docs](https://docs.imagekit.io/features/image-transformations/resize-crop-and-other-transformations#border-b)

But the SDK is using `bo`

**Comment by utk0730** [comment]
Hi, may i work on this issue for Hacktoberfest ?

**Comment by imagekitio** [comment]
@utk0730 Yes, you can 👍

**Comment by imagekitio** [comment]
@TheLearneer version `1.3.5` has this fix along with test cases.
