### ISSUE TITLE
How can i get the upload percentage

### ISSUE THREAD

**Issue by raghavmri** [imagekit-developer/imagekit-javascript#25]
I am using image kit-js to upload my profile pic images of my users but when they upload i wanna show them the percent they have uploaded is there any way to get that percentage

**Comment by imagekitio** [comment]
@gogamic Makes sense.

How about an event or callback method with upload progress?

How would you like to use it in your application?

**Comment by gogamic** [comment]
@imagekitio indeed so I wanna display my users the progress of the upload

**Comment by gogamic** [comment]
also any way I can contribute to this?

**Comment by imagekitio** [comment]
@gogamic sure. Please share the syntax of callback and data structure of response. Then you can proceed to actual implementation.

**Comment by gogamic** [comment]
i need some time to prepare it

**Comment by gogamic** [comment]
@imagekitio is it possible to mail me privately please

**Comment by Plausible0Bug** [comment]
Will you simply expose the XHR in your API?
This will also allow aborting the request if needed.

**Comment by imagekitio** [comment]
That sounds good. We will shortly release a new version with these changes.

**Comment by imagekitio** [comment]
https://github.com/imagekit-developer/imagekit-javascript#tracking-upload-progress-using-custom-xmlhttprequest
