### ISSUE TITLE
support for responsive images?

### ISSUE THREAD

**Issue by JerryGoyal** [imagekit-developer/imagekit-javascript#3]
I may have missed it but I couldn't find the way to serve responsive images in imagekit. something like `"width" : "auto"` which is then calculated at runtime inside user's browser by ` js`.

**Comment by imagekitio** [comment]
@JerryGoyal  - ImageKit.io provides support for client hints which can simplify your code. Please check this article - https://scotch.io/tutorials/deliver-responsive-and-art-directed-images-for-your-website-with-imagekit908237
