### ISSUE TITLE
New release for types property in package.json

### ISSUE THREAD

**Issue by harrygr** [imagekit-developer/imagekit-javascript#43]
#39 fixes the issue of types not being automatically resolved for the package when installed as a dependency.

However since merge there has not been a release of the package.

Can a release please be made so we can benefit from this change.

---

In the meantime you can add the following to your project's tsconfig.json, telling TS where to find the types for `imagekit-javascript`:

```
{
  "compilerOptions": {
    //...
    "baseUrl": ".", // This must be specified if "paths" is.
    "paths": {
      "imagekit-javascript": ["node_modules/imagekit-javascript/dist/src"] // This mapping is relative to "baseUrl"
    }
  }
}
```

**Comment by imagekitio** [comment]
Thanks @harrygr. Version 1.4.1 released.
