### ISSUE TITLE
How to pass jwt to get Sign 

### ISSUE THREAD

**Issue by digiwala** [imagekit-developer/imagekit-javascript#49]
How to pass jwt (Auth token) to get Sign from my server

**Comment by imagekitio** [comment]
Please refer to this documentation - https://docs.imagekit.io/api-reference/upload-file-api/client-side-file-upload#how-to-implement-authenticationendpoint-endpoint
Examples - https://docs.imagekit.io/api-reference/upload-file-api/client-side-file-upload#examples
