### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by tylercollier** [imagekit-developer/imagekit-javascript#7]
Can you add the ability to specify a timeout, or default it to some value? XHR has no timeout by default. I just spent a while debugging why my use of `imagekit.upload()` wasn't working OR giving me an error. It's because I was (accidentally) specifying an inaccessible endpoint, but I couldn't figure out why there was no error. It because the XHR's `onload` was never called.

**Comment by imagekitio** [comment]
Thanks for the feedback. We will provide a timeout option with a default value in the next release.

**Comment by imagekitio** [comment]
A default timeout of 60 seconds is set on the authentication endpoint. Considering this is something that should be identified during development, I didn't make this option configurable at this point.

**Comment by tylercollier** [comment]
I used the wrong endpoint, so a timeout on your side won't help. It was my fault, but, hard to debug and would have been easier if I had gotten an error like "timeout of 60 seconds has been reached".

**Comment by imagekitio** [comment]
I am sorry for the confusion. What I mean is that a timeout of 60 seconds has been set now in the latest release. You can test it in version 1.2.1. If the endpoint is wrong, `.upload` will throw an error after 60 seconds.

**Comment by tylercollier** [comment]
Ah! Totally my mistake, what you said makes sense, but I read it wrong.

I did upgrade to 1.2.1 because of #8. My app is working in development and production now. Thanks!
