### ISSUE TITLE
Is it possible to use imageKit for playing video in react-native?

### ISSUE THREAD

**Issue by zahrat** [imagekit-developer/imagekit-javascript#78]
I read the documentation of ImageKit but I couldn't find anything about ImageKit and video in react-native. Does it support video for react native?

**Comment by ankur-dwivedi** [comment]
Hey @zahrat, you can use the [react-native-video](https://www.npmjs.com/package/react-native-video) package to play video files. Check out the example code below, or visit https://docs.imagekit.io/getting-started/quickstart-guides/react-native for more details.

```javascript
          import Video from 'react-native-video
          <Video
            source={{uri: 'https://ik.imagekit.io/demo/img/sample-video.mp4'}}
            style={{
              width: 200,
              height: 200,
            }}
            controls={true}
          />
```
