### ISSUE TITLE
URLSearchParams

### ISSUE THREAD

**Issue by tylercollier** [imagekit-developer/imagekit-javascript#8]
Would you consider allowing developers to specify the URLSearchParams implementation? The situation I'm running into is with React Native. When I use `imagekit.url(...)`, I get the error `not implemented`. This is due to [a bug in React Native](https://github.com/facebook/react-native/issues/23922). There is [a way to get around it](https://github.com/facebook/react-native/issues/23922#issuecomment-476070032), but this [bloats the bundle size](https://github.com/facebook/react-native/issues/23922#issuecomment-482349551), so it'd be better if I could instead include another implementation of `URLSearchParams`, such as [this one](https://github.com/jerrybendy/url-search-params-polyfill). I'm guessing you'd do it like this:

```js
const URLSearchParamsPolyfill = require('url-search-params-polyfill');

var imagekit = new ImageKit({
    publicKey : "your_public_api_key",
    urlEndpoint : "https://ik.imagekit.io/your_imagekit_id",
    authenticationEndpoint : "http://www.yourserver.com/auth",
    URLSearchParams: URLSearchParamsPolyfill,
});  
```

**Comment by imagekitio** [comment]
It seems that if we use `. append` method which is [implemented](https://github.com/facebook/react-native/blob/e6057095adfdc77ccbbff1c97b1e86b06dae340b/Libraries/Blob/URL.js#L61) instead of `.set` then it will work.

Please test the changes in latest version 1.2.1

**Comment by tylercollier** [comment]
It works, thanks!

**Comment by rpavlovs** [comment]
Getting the same error on `1.3.7`. This time it's `.pathname`

`yarn.lock` diff shows that `url-polyfill` was dropped when updating from `1.2.3`
