### ISSUE TITLE
Add Support for List and search file API

### ISSUE THREAD

**Issue by snlpatel001213** [imagekit-developer/imagekit-javascript#88]

**Comment by ankur-dwivedi** [comment]
Hi @snlpatel001213, currently, you can use the [Imagekit Node.js SDK](https://github.com/imagekit-developer/imagekit-nodejs?tab=readme-ov-file#file-management) for accessing the list and search file API. Alternatively, if you're working on the front-end, you can directly use our API  `https://api.imagekit.io/v1/files`. For further details, please refer to our [documentation](https://docs.imagekit.io/api-reference/media-api/list-and-search-files#list-and-search-file-api).
